language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
matrix:
  allow_failures:
  - julia: nightly
after_success:
 - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
